name: scout
channels:
  - defaults
dependencies:
  - arrow-cpp=4.0.1
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - blas=1.0
  - boost-cpp=1.73.0
  - bottleneck=1.3.4
  - brotli=1.0.9
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.4.26
  - certifi=2021.10.8
  - cycler=0.11.0
  - double-conversion=3.1.5
  - fastparquet=0.5.0
  - fonttools=4.25.0
  - freetype=2.11.0
  - gflags=2.2.2
  - giflib=5.2.1
  - glog=0.5.0
  - grpc-cpp=1.26.0
  - icu=58.2
  - intel-openmp=2021.4.0
  - jpeg=9e
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - libboost=1.73.0
  - libcurl=7.82.0
  - libcxx=12.0.0
  - libedit=3.1.20210910
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.3
  - libiconv=1.16
  - libllvm11=11.1.0
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libprotobuf=3.11.2
  - libssh2=1.10.0
  - libthrift=0.13.0
  - libtiff=4.2.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - llvm-openmp=12.0.0
  - llvmlite=0.38.0
  - lz4-c=1.9.3
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - numba=0.55.1
  - numexpr=2.8.1
  - numpy=1.21.2
  - numpy-base=1.21.2
  - openssl=1.1.1o
  - orc=1.6.7
  - packaging=21.3
  - pandas=1.4.2
  - pillow=9.0.1
  - pip=21.2.4
  - plotly=5.6.0
  - pyarrow=4.0.1
  - pyparsing=3.0.4
  - python=3.9.7
  - python-dateutil=2.8.2
  - pytz=2021.3
  - re2=2022.04.01
  - readline=8.1.2
  - setuptools=58.0.4
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.37.0
  - tbb=2021.5.0
  - tenacity=8.0.1
  - thrift=0.11.0
  - tk=8.6.11
  - tornado=6.1
  - tzdata=2021e
  - uriparser=0.9.3
  - utf8proc=2.6.1
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - coverage==6.3.3
    - distlib==0.3.4
    - filelock==3.7.0
    - platformdirs==2.5.2
    - pluggy==1.0.0
    - py==1.11.0
    - toml==0.10.2
    - tox==3.25.0
    - virtualenv==20.14.1
