name: CodeCov
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  CodeCov:
    runs-on: macOS-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: scout
          auto-activate-base: false

      - run: conda --version
      - run: which python
      - name: Generate coverage report
        run: |
          coverage run -m unittest discover
          coverage xml
          coverage json
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

