name: scout-package-tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  scout-package-tests:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.py }})

    strategy:
      matrix:
        config:
          - {os: ubuntu-latest, py: "3.6"}
          - {os: ubuntu-latest, py: "3.7"}
          - {os: ubuntu-latest, py: "3.8"}
          - {os: ubuntu-latest, py: "3.9"}

    steps:
      - name: Get contents from tip of branch on push
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.config.py }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          active-environment: scout
          environment-file: environment.yml
          python-version: ${{ matrix.config.py }}
      - name: tox
        run: |
          tox

