name: scout-package-tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  scout-package-tests:
    runs-on: macOS-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: scout
          auto-activate-base: false

      - run: conda --version
      - run: which python
      - name: tox
        run: |
          tox

