name: scout-package-tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  scout-package-tests:
    runs-on: ${{ matrix.os }}

    name : ${{ matrix.os }} - py ${{ matrix.python-version }}

    strategy:
      matrix:
        os: ["macOS-latest", "ubuntu-latest"]
        python-version: ["3.6", "3.7", "3.8", "3.9"]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: scout
          auto-activate-base: false
          python-version: ${{ matrix.python-version }}

      - name: Conda Info
        run: conda info

      - name: py-version
        run : python --version

      - name: tox
        run: |
          tox

