name: scout-package-tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  scout-package-tests:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (${{ matrix.python-version }})

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge

      - run: conda --version
      - run: which python
      - name: tox
        run: |
          tox

